/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.berg.mylegislator;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int democratic_gradient=0x7f050007;
        public static final int democratic_panel=0x7f050006;
        public static final int independant_gradient=0x7f050009;
        public static final int independant_panel=0x7f050008;
        public static final int republican_gradient=0x7f050005;
        public static final int republican_panel=0x7f050004;
        public static final int solid_blue=0x7f050001;
        public static final int solid_green=0x7f050002;
        public static final int solid_red=0x7f050000;
        public static final int solid_yellow=0x7f050003;
    }
    public static final class drawable {
        public static final int blue=0x7f020011;
        public static final int democrat_divider=0x7f020000;
        public static final int democrat_icon=0x7f020001;
        public static final int democratic_list_selector_background=0x7f020002;
        public static final int green=0x7f020012;
        public static final int icon=0x7f020003;
        public static final int list_selector_background_disabled=0x7f020004;
        public static final int list_selector_background_focus_democrate=0x7f020005;
        public static final int list_selector_background_focus_republican=0x7f020006;
        public static final int list_selector_background_longpress=0x7f020007;
        public static final int list_selector_background_pressed=0x7f020008;
        public static final int list_selector_background_pressed_democrate=0x7f020009;
        public static final int list_selector_background_pressed_republican=0x7f02000a;
        public static final int list_selector_background_transition=0x7f02000b;
        public static final int progress_circular_indeterminate=0x7f02000c;
        public static final int red=0x7f020010;
        public static final int republican_divider=0x7f02000d;
        public static final int republican_icon=0x7f02000e;
        public static final int republican_list_selector_background=0x7f02000f;
        public static final int screen_background_black=0x7f020014;
        public static final int translucent_background=0x7f020015;
        public static final int transparent_background=0x7f020016;
        public static final int yellow=0x7f020013;
    }
    public static final class id {
        public static final int add_legislator_to_contacts=0x7f080035;
        public static final int add_to_twitter=0x7f080031;
        public static final int address=0x7f080013;
        public static final int address_row=0x7f080012;
        public static final int call_legislator=0x7f080032;
        public static final int cell_width=0x7f08000e;
        public static final int chatview=0x7f080008;
        public static final int committees_list=0x7f080003;
        public static final int continue_to_welcome_intent=0x7f08001d;
        public static final int display_term=0x7f080023;
        public static final int district=0x7f080007;
        public static final int email=0x7f08000c;
        public static final int email_legislator=0x7f080033;
        public static final int email_row=0x7f08000b;
        public static final int enter_zip_button=0x7f08002b;
        public static final int enter_zip_edit_text=0x7f08002a;
        public static final int fax=0x7f080011;
        public static final int fax_row=0x7f080010;
        public static final int first_name=0x7f080021;
        public static final int fullname=0x7f080006;
        public static final int indicator_progress_bar=0x7f080028;
        public static final int indicator_row=0x7f080027;
        public static final int indicator_text=0x7f080029;
        public static final int input_screen_message=0x7f080026;
        public static final int legislator_inner_panel=0x7f080002;
        public static final int legislator_panel=0x7f080005;
        public static final int legislators_list=0x7f08001f;
        public static final int main_panel=0x7f08001e;
        public static final int main_title=0x7f080001;
        public static final int mini_bio=0x7f08002c;
        public static final int no_legislators_panel=0x7f08001c;
        public static final int party=0x7f080022;
        public static final int party_icon=0x7f080020;
        public static final int phone=0x7f08000f;
        public static final int phone_row=0x7f08000d;
        public static final int requery_legislators=0x7f080036;
        public static final int reset=0x7f080037;
        public static final int s=0x7f080004;
        public static final int term_ends=0x7f08000a;
        public static final int term_ends_row=0x7f080009;
        public static final int term_panel=0x7f080000;
        public static final int term_title=0x7f080024;
        public static final int terms=0x7f08002d;
        public static final int terms_list=0x7f080025;
        public static final int twitter=0x7f080019;
        public static final int twitter_row=0x7f080018;
        public static final int visit_webform_additional=0x7f08002f;
        public static final int visit_webform_main=0x7f080034;
        public static final int visit_website=0x7f08002e;
        public static final int visit_youtube_channel=0x7f080030;
        public static final int webform_row=0x7f080016;
        public static final int webform_url=0x7f080017;
        public static final int website_row=0x7f080014;
        public static final int website_url=0x7f080015;
        public static final int youtube=0x7f08001b;
        public static final int youtube_row=0x7f08001a;
    }
    public static final class layout {
        public static final int committees=0x7f030000;
        public static final int expandable_list_view=0x7f030001;
        public static final int legislator=0x7f030002;
        public static final int main=0x7f030003;
        public static final int my_legislator_main_rows=0x7f030004;
        public static final int term_adapter=0x7f030005;
        public static final int terms=0x7f030006;
        public static final int welcome=0x7f030007;
    }
    public static final class menu {
        public static final int additional_options=0x7f070000;
        public static final int legislator=0x7f070001;
        public static final int main=0x7f070002;
    }
    public static final class string {
        public static final int add_legislator_to_contacts_label=0x7f06000b;
        public static final int add_legislator_to_contacts_shortcut=0x7f06000c;
        public static final int add_to_twitter_label=0x7f06000d;
        public static final int add_to_twitter_shortcut=0x7f060010;
        /** Legislator Additional Options
         */
        public static final int additional_options=0x7f06000f;
        public static final int app_name=0x7f060000;
        /** Legislator Main Options
         */
        public static final int call_legislator_label=0x7f060007;
        public static final int call_legislator_shortcut=0x7f060008;
        public static final int email_legislator_label=0x7f060009;
        public static final int email_legislator_shortcut=0x7f06000a;
        /**  No Legislators Found on Main Itent 
         */
        public static final int empty_cursor=0x7f060001;
        public static final int enter_zip_button_text=0x7f060004;
        public static final int regular_message=0x7f060003;
        public static final int remove_legislator_to_contacts_label=0x7f06000e;
        /** Main Options
         */
        public static final int requery_legislator_label=0x7f060005;
        public static final int requery_legislator_shortcut=0x7f060006;
        public static final int visit_youtube_channel_label=0x7f060011;
        public static final int visit_youtube_channel_shortcut=0x7f060012;
        /**  Welcome Intent Strings 
         */
        public static final int welcome_message=0x7f060002;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
}
